### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by dev-mamun** [torobucci/Book-collection#4]
Hi 👋

- ## To Highlight
- Descriptive README ✔️ 
- Good job on implementing the correct GitHub workflow ✔️ 
- Correct linters setup  ✔️
-  Good implementation of the JavaScript functionality ✔️  

 ## Issues
I would like to suggest an issue to make your repo better

- Unfortunately, the live demo link does not work. I suggest you add the correct working link so everyone can visit and view your work.

**Comment by torobucci** [comment]
@dev-mamun  Thanks for the suggestion. I've now published my repo
